#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

shopt -s extglob

rm -rf !(0|constant|system|AllClean|*.OpenFOAM|*.pvsm)


#------------------------------------------------------------------------------
