#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Enable bash script
shopt -s extglob

# Clear screen
clear

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
blockMesh

# Running in serial in Default

echo ">>> Simulation in parallel?     y -> YES    n -> NO"
read -t 3 SimMode


# Serial run
if [ "$SimMode" = "n" ]; then
	# Run single core
	$(getApplication)
fi

# Parallel run
if [ "$SimMode" = "y" ]; then
	# Decompose 8 domain
	decomposePar
	# Mpi run
	mpirun -np $(getNumberOfProcessors) $(getApplication) -parallel
	
	echo
	echo

	# Reconstruct partition
	reconstructPar
fi


#------------------------------------------------------------------------------
